modLoader="javafml"
loaderVersion="[47,)"
license="Not specified"

[[mods]]
modId="fuetcraft"
version="1.0.0"
displayName="fuetcraft"
displayURL="https://github.com/fuetland/fuetcraft"
logoFile="logo.png"
credits="fuetland@gmail.com"
authors="Fuetland"
description="This mod includes the ability to craft different types of Fuets. Each of these provides different effects for the adventure."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.fuetcraft]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration